### ISSUE TITLE
ESC to close post composer

### ISSUE THREAD

**Issue by sabigara** [sabigara/flat#17]
<img width="611" alt="Screenshot 2023-04-23 12 10 00" src="https://user-images.githubusercontent.com/41217985/233817604-48d2ca53-6831-4ffd-90f8-c24d81662b6c.png">

https://github.com/sabigara/flat/blob/main/src/app/post/components/PostComposer.tsx#L147

The above component is using [Headless UI](https://headlessui.com/react/dialog) which should support "ESC to close" out of the box, but not working for some reason.

## Environment

- Chrome (112.0.5615.137), Safari (16.4)
- macOS (13.3.1)

Can't reproduce with Firefox.

**Comment by flbn** [comment]
can't reproduce? assuming you patched in this commit? https://github.com/sabigara/flat/commit/2f14f7c0458fd0fb1e3f8de48a3517a91b6a9af5

**Comment by sabigara** [comment]
I didn't fix this in the commit.

Hum, seems this is a browser-specific issue…. I can't close on Chrome and Safari but Firefox does it well (on Mac). What's your environment? It would be helpful if you retry with other browsers.

**Comment by sabigara** [comment]
FYI, I'm working on i18n and it's almost done with the English translation. Visit the below link in case you are in trouble with Japanese UI text.

https://flat-git-i18n-sabigara.vercel.app

It should automatically display English text but you can select the language on [settings page](https://flat-git-i18n-sabigara.vercel.app/settings) (change "言語").

**Comment by flbn** [comment]
oooo, yea that PR is nice! can confirm, english translation without needing to go on settings.

**Comment by sabigara** [comment]
Oops, turned out [Vimium](https://github.com/philc/vimium) on my Chrome and Safari is preventing the behavior in some ways… What's weird is that ESC key itself seems just working but maybe something is going wrong internally.

Sorry for taking your time but this wasn't a bug! If you still want to cotribute to this project, I will make some issues.
