### ISSUE TITLE
looking to contribute, don't have an invite code. how can i help?

### ISSUE THREAD

**Issue by flbn** [sabigara/flat#26]
title says all. have been studying the protocol & find it pretty interesting. wondering if there's anything i can help w until i get one of those invites req to create an account?

**Comment by sabigara** [comment]
You can run a local dev server (PDS) just by:

1. Clone https://github.com/bluesky-social/atproto
2. `yarn install`
3. `make run-dev-env`

And you should be able to create an account by an official app (no matter web or mobile).

If you'd like to contribute, resolving #17 should be worth an invite code 😸

**Comment by flbn** [comment]
hmmm. i'm able to create an account locally (@maudlin.test) but only able to sign into the local dev server... i can create an app password, but get the following error: `Invalid identifier or password`. the network call itself is saying that it's hitting the bluesky servers to log me in, but as i stated before the credentials i set up only work locally...

**Comment by sabigara** [comment]
You can't sign in to bsky.social by credentials for the dev server. I think an account in your local dev server is enough for development like #17.

What are you trying to do?

**Comment by flbn** [comment]
nvm, i got an official account and was able to make the app password work!
