### ISSUE TITLE
Profile picture displays incorrectly on Firefox

### ISSUE THREAD

**Issue by n1ckoates** [sabigara/flat#32]
On Firefox, the avatar on a profile page displays full sized underneath the banner, rather than scaled down on top of it. Here's my profile on Firefox (left) and Chromium (right).

![image](https://user-images.githubusercontent.com/58091943/235321020-458df60d-3cc0-4cc6-b9ef-2968cebc7062.png)

This is almost definitely because `cqw` units are still experimental on Firefox - enabling `layout.css.container-queries.enabled` in `about:config` fixes this issue. I'm not sure what the workaround for this would be.

**Comment by sabigara** [comment]
Thank you for reporting this issue.

But not sure why the `cqw` isn't working – it should be supported by the latest Firefox without the flag according to [caiuse](https://caniuse.com/css-container-query-units). Is your Firefox up to date?

**Comment by n1ckoates** [comment]
The version caniuse is testing on is still in beta from what I can tell. This shouldn't be much of an issue then, because it will be fixed on stable in a few weeks.
